apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-ms
  namespace: checkout-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-ms
  template:
    metadata:
      labels:
        app: checkout-ms
    spec:
      containers:
        - name: checkout-ms
          image: $ECR_REGISTRY/$ECR_REPOSITORY:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m       # Solicita 100 milicores de CPU
              memory: 256Mi   # Solicita 256 Mebibytes de memória
            limits:
              cpu: 1000m       # Limita a 200 milicores de CPU
              memory: 512Mi   # Limita a 512 Mebibytes de memória
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10