apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: checkout-namespace
spec:
  selector:
    app: checkout-ms
  ports:
    - port: 80
      targetPort: 8989
  type: LoadBalancer
  
