apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: checkout-namespace
spec:
  selector:
    app: checkout-ms
  ports:
    - port: 80
      targetPort: 8989
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-arn: arn:aws:elasticloadbalancing:us-east-1:643230847802:loadbalancer/net/fiap-burger-lb-checkout/e8bc3f4fc443a6a1
