name: Deploy to EKS

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Adoptium Temurin é uma das distribuições mais usadas
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 6: Build Docker image
      - name: Build Docker image checkout
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      # Step 7: Push Docker image to Amazon ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

      # Step 8: Update kubeconfig to use EKS cluster
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Create namespace
        run: |
          kubectl apply -f infra/namespace-checkout.yml

      - name: Substitute variables in deployment.yml
        run: |
          envsubst < infra/deployment.yml > infra/deployment_substituted.yml
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          GITHUB_SHA: ${{ github.sha }}

      - name: Deploy application checkout
        run: |
          kubectl apply -f infra/deployment_substituted.yml -n checkout-namespace

      - name: Create service
        run: |
          kubectl apply -f infra/service.yml -n checkout-namespace

      #- name: Wait for rollout to finish
        #run: |
          #kubectl rollout status deployment/checkout-ms -n checkout-namespace
          #TO DO arruma readnessProbe para acionar essa verificação